
root:
- changed-files:
  - any-glob-to-any-file: '*'

# Label changes to SQLX definitions
sqlxdefinitions:
- changed-files:
  - any-glob-to-any-file: definitions/**/*.sql

changes-in-dwh:
- changed-files:
  - any-glob-to-any-file: definitions/dwh/**.sql

changes-in-int:
- changed-files:
  - any-glob-to-any-file: definitions/intermediate/**.sql

changes-in-stg:
- changed-files:
  - any-glob-to-any-file: definitions/staging/**.sql

ci-cd: 
- changed-files: 
  - any-glob-to-any-file: .github/workflows/**/*.yml
