name: Check Pull Request Quality
on: pull_request
jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
    - name: Check PR title
      env:
        TITLE: ${{ github.event.pull_request.title }}
      run: |
        if [[ "$TITLE" =~ ^feat ]]; then
        echo "PR title starts with 'feat'"
        exit 0
        else
        echo "PR title did not start with 'feat'..."
        exit 1
        fi