name: Check Pull Request Quality
on: pull_request
jobs:
  check-pull-request: 
    runs-on: ubuntu-latest
    steps:
    - name: Check title
      env:
        TITLE: ${{ github.event.pull_request.title }}
      run: |
        if [[ "$TITLE" =~ ^feat ]]; then
        echo "Your PR title ($TITLE) starts with 'feat'"
        exit 0
        else
        echo "PR title did not start with 'feat'..."
        exit 1
        fi
    - name: Check Description 
      env: 
        DESCRIPTION: ${{ github.event.pull_request.body }}
      run: |
        if [[ ${#DESCRIPTION} == 0 ]]; then
        echo "No description provided. Please add one. (${#DESCRIPTION})"
        exit 1
        else 
        echo "Description check passed."
        exit 0
        fi